### ISSUE TITLE
Appears this is for FTrack db

### ISSUE THREAD

**Issue by elalande** [kiryha/AnimationDNA#1]
Thank you so much for this It is helping me a lot ,but it seems everything is looking for a FTrack DB and not the JSON db, even the setupProject.py says its the FTRACK Edition.

**Comment by kiryha** [comment]
Hello!
setupProject.py fixed
setupMaya.py fixed

Other tools checked, should be fine.
Cheers!

**Comment by elalande** [comment]
Thank you very much for the fast update, I hope Im not being a pain, but I see there is no .bat file, if its a matter of just running the python file I have that covered but its still not reading the userSetup.mel in the project dir , I've setup the directory  structure as its outlined on your site but its not reading it.

Again thank you for providing this pipeline.

**Comment by kiryha** [comment]
Hello, elalande!
I add .bat files. 
Can you post all messages from script editor after Maya has launched?

**Comment by elalande** [comment]
Sorry everything is working now,didnt have the original folder structure and python script was case sensitive but its working great, working on Houdini scripts :D thanks again
