### ISSUE TITLE
Hi Kriryha 

### ISSUE THREAD

**Issue by tws0002** [kiryha/AnimationDNA#3]
hi Kriryha,
Thanks for sharing this pipeline. I try using AnimationDNA pipeline, it was good. but having a problem when adding task for asset, shot, and etc!! Do u have any tools that we can use to assign task in JSON?
for those who don't have PFTrack.

Thanks 
Desmond

**Comment by kiryha** [comment]
Hello, Desmond!
I know it could be hard to manage a big amount of assets with JSON.
Unfortunately, JSON is alternative to FTrack and I don't have any ideas how to make life easier other than using FTrack or another usable tracking tool like Shotgun.

**Comment by kiryha** [comment]
Can you describe what problems you have with adding tasks more in depth? 
Also, I had an idea to use any advanced but free tracking system instead JSON and i found only TACTIC. The problem with tactic is that its way to complex and not user friendly.

**Comment by tws0002** [comment]
Thanks for the quick reply. 
I agree Tactic is friendly enough!! my problem is how to create a big JSON database if I have a movie project that have more 100plus asset 500 Shots!! is hard to key in manually with JSON project temple u provide!! 

I have found this https://github.com/listyque/TACTIC-Handler for tactic!! but is still in development!! 

Hope you can give some advice if I using AnimationDNA pipeline workflow.

Thanks 
Desmond

**Comment by kiryha** [comment]
Well, the idea is that JSON is a free version of AnimationDNA for a small or personal projects. If you have 500 shots in production, then you should afford 20$ each month to get FTrack, it worth it even if the project is noncommercial I think. 

BTW, do u use [online editor](http://www.jsoneditoronline.org/ ) for database? You can manage dictionary in a more easy way than in text editor ( duplicating items for example ).

**Comment by kiryha** [comment]
I saw your link about TACTIC but it would not help me at this stage. You can work with FTrack after several minutes your see it the first time, but TACTIC ... 
If Ftrack is not an option for you then I can only advise being patient with JSON :)

**Comment by tws0002** [comment]
Thanks for the advice!! I never try online editor before!! but will give it a try.
Do you provide an FTrack version of AnimationDNA? Maybe I can download Ftrack trial version.

Thanks 
Desmond

**Comment by kiryha** [comment]
That's what it is — a trial version :) The ftrack version totally the same in terms of CG production, it just retrieves information not from a text file, but from ftrack database.

**Comment by tws0002** [comment]
Great!! i will try to use online editor to test run simple project.
Thanks for helping this industry!! 

Desmond

**Comment by kiryha** [comment]
You are welcome!
The DNA.rar already contain simple test project data including JSON database.
The best way to start, I guess, its [Quick Start Tutorial](https://github.com/kiryha/AnimationDNA/wiki/01-Quick-start)
