### ISSUE TITLE
hi kiryha 

### ISSUE THREAD

**Issue by tws0002** [kiryha/AnimationDNA#4]
Hi Kiryha,

hey Kiryha are you going to bridge houdini into AnimationDNA soon?

Thanks
Desmond

**Comment by kiryha** [comment]
Exactly!
No tools expected, for now, just folder structure because I stack at the beginning - [can't run Houdini from wrapper ](http://stackoverflow.com/questions/41514143/run-program-on-mac-os-with-python-fails/41526333?noredirect=1#comment70352698_41526333)

**Comment by tws0002** [comment]
Hey Kiryha i not sure this will help you. 
here is the link u can check out https://github.com/tws0002/vray-for-houdini/blob/master/deploy/hfs_osx.sh.in 
maybe u are looking for this?

Desmond
