### ISSUE TITLE
Hey Kiryha i not sure this will help you not!!

### ISSUE THREAD

**Issue by tws0002** [kiryha/AnimationDNA#5]
Hey Kiryha i not sure this will help you.
here is the link u can check out https://github.com/tws0002/vray-for-houdini/blob/master/deploy/hfs_osx.sh.in
maybe u are looking for this?

Desmond

**Comment by kiryha** [comment]
Hello, Desmond! Thanks for the link, probably will help me later if I will write Houdini tools also.

How it's going with online JSON editor? Filling and editing database should be not so painful compared to the regular text editor.

**Comment by tws0002** [comment]
yeap JSON editor is very helpful. save me tons of time!! 
Do u mind I email in person? bcos I have some question to ask. 

Thanks 
Desmond

**Comment by kiryha** [comment]
Sure! 
kiryha@gmail.com
